# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- demo

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: build
    displayName: Build images
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Web image
      inputs:
        command: buildAndPush    
        containerRegistry: 'ttl.sh'
        repository: 'slackernews-web'
        dockerfile: '$(Build.SourcesDirectory)/deploy/Dockerfile.web'
        tags: '2h'
    - task: Docker@2
      displayName: Build Web image
      inputs:
        command: buildAndPush    
        containerRegistry: 'ttl.sh'
        repository: 'slackernews-nginx'
        dockerfile: '$(Build.SourcesDirectory)/deploy/Dockerfile.web'
        tags: '2h'

- stage: Release
  displayName: Release
  jobs:
  - job: build
    displayName: Build images
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'make chart'
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: false
    
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          cd chart/slackernews && \
            helm dep up --debug && \
            cd .. && \
            helm package \
              --app-version=1.0.0 \
              --version=1.0.0 \
              ./slackernews
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'charts'
        Contents: 'slackernews*.tgz'
        TargetFolder: 'kots'