# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- demo

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build images
  jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Web image
      inputs:
        command: buildAndPush    
        containerRegistry: 'ttl.sh'
        repository: 'slackernews-web'
        dockerfile: '$(Build.SourcesDirectory)/deploy/Dockerfile.web'
        tags: '2h'
    - task: Docker@2
      displayName: Build Web image
      inputs:
        command: buildAndPush    
        containerRegistry: 'ttl.sh'
        repository: 'slackernews-nginx'
        dockerfile: '$(Build.SourcesDirectory)/deploy/Dockerfile.web'
        tags: '2h'
